# Higher-level group analysis

This notebook demonstrates the higher (second) level group analysis steps for the synthetic dataset.

It first uses the interactive python interface to perform the analysis, before demonstrating the equivalent command line steps.

Some plotting of the group results is also carried out.

## 1. First-level (single-subject) contrasts

The first step of this process is actually to construct contrasts of interest from the raw fitted betas of each subject.  
At the same time we also take the opportunity to sum any metabolites which typically show substantial (negative) correlation.

Tools for fMRS stats are contained in the `fsl_mrs.utils.fmrs_tools` package of FSL-MRS.


### 1.1 Assemble the locations fot he first-level fits.
We want all the stim results and then all the ctrl results, each sorted by subject number. This simplified making the higher-level design matrices later.

In [330]:
from pathlib import Path
# Create a list of the results directories
firstlevel_results_dir = Path('first_level_results')

subject_results_stim = []
subject_results_ctrl = []
for file in firstlevel_results_dir.rglob('free_parameters.csv'):
    if file.parent.name == 'stim':
        subject_results_stim.append(str(file.parent))
    else:
        subject_results_ctrl.append(str(file.parent))

subject_results = sorted(subject_results_stim) + sorted(subject_results_ctrl)
print(subject_results)

['first_level_results/sub0/stim', 'first_level_results/sub1/stim', 'first_level_results/sub2/stim', 'first_level_results/sub3/stim', 'first_level_results/sub4/stim', 'first_level_results/sub5/stim', 'first_level_results/sub6/stim', 'first_level_results/sub7/stim', 'first_level_results/sub8/stim', 'first_level_results/sub9/stim', 'first_level_results/sub0/ctrl', 'first_level_results/sub1/ctrl', 'first_level_results/sub2/ctrl', 'first_level_results/sub3/ctrl', 'first_level_results/sub4/ctrl', 'first_level_results/sub5/ctrl', 'first_level_results/sub6/ctrl', 'first_level_results/sub7/ctrl', 'first_level_results/sub8/ctrl', 'first_level_results/sub9/ctrl']


### 1.2 Describe the new contrasts we are going to make

This includes summing the betas of highly (negatively) correlated peaks, e.g. NAA/NAAG, Cr/PCr, and averaging the two activation block betas (0 & 1).

There is a dataclass to help with the description of the contrasts.

In [336]:
import fsl_mrs.utils.fmrs_tools as fmrs

# Form mean activation contrasts take mean of two betas (i.e. 0.5 * beta0 + 0.5 * beta1)
contrasts = [
    fmrs.Contrast(
        'mean_activation',
        ['beta0', 'beta1'],
        [0.5, 0.5])]

metabo_comb = [['PCh','GPC'],
              ['Cr','PCr'],
              ['NAA', 'NAAG'],
              ['Glu', 'Gln']]

### 1.3 Use the FSL-MRS tools to linearly combine values and propagate variances.

We save the output betas (which include the original ones as well) and the variances on each beta.

In [344]:
import numpy as np

modified_betas = []
modified_var = []

for res_path in subject_results:
    _, _, df, new_params = fmrs.create_contrasts(res_path, contrasts=contrasts, metabolites_to_combine=metabo_comb)

    modified_betas.append(df['mean'].to_numpy())
    modified_var.append(df['sd'].pow(2).to_numpy())

# Stack the results of all the subjects together.
all_betas = df.index
modified_betas = np.stack(modified_betas)
modified_var = np.stack(modified_var)

# Display new contrasts of one subject
df.loc[new_params]

mean        sd
conc_PCh+GPC_beta0             0.001036  0.000798
conc_PCh+GPC_beta1             0.000606  0.001069
conc_PCh+GPC_beta2            -0.000455  0.001428
conc_PCh+GPC_beta3             0.041575  0.000512
conc_Cr+PCr_beta0             -0.000230  0.001816
conc_Cr+PCr_beta1              0.000933  0.002378
conc_Cr+PCr_beta2              0.000544  0.003096
conc_Cr+PCr_beta3              0.353186  0.001230
conc_NAA+NAAG_beta0            0.000507  0.001950
conc_NAA+NAAG_beta1            0.007049  0.002569
conc_NAA+NAAG_beta2           -0.007825  0.003362
conc_NAA+NAAG_beta3            0.614349  0.001332
conc_Glu+Gln_beta0             0.002648  0.005707
conc_Glu+Gln_beta1            -0.006709  0.006622
conc_Glu+Gln_beta2             0.023885  0.006778
conc_Glu+Gln_beta3             0.532341  0.003591
conc_Asc_mean_activation      -0.002270  0.003689
conc_Asp_mean_activation      -0.008278  0.006055
conc_Cr_mean_activation       -0.003776  0.004328
conc_GABA_mean_activation      0.003750  0.005766
conc_GPC_mean_activation       0.001410  0.002100
conc_GSH_mean_activation      -0.000839  0.002130
conc_Glc_mean_activation       0.000840  0.003988
conc_Gln_mean_activation       0.005063  0.005240
conc_Glu_mean_activation      -0.007093  0.004294
conc_Ins_mean_activation       0.002651  0.002350
conc_Lac_mean_activation       0.003500  0.002352
conc_Mac_mean_activation      -0.000135  0.000306
conc_NAA_mean_activation       0.004906  0.001821
conc_NAAG_mean_activation     -0.001128  0.001584
conc_PCh_mean_activation      -0.000589  0.002094
conc_PCr_mean_activation       0.004128  0.004249
conc_PE_mean_activation       -0.004071  0.004776
conc_Scyllo_mean_activation   -0.000203  0.000836
conc_Tau_mean_activation      -0.000835  0.003101
conc_PCh+GPC_mean_activation   0.000821  0.000737
conc_Cr+PCr_mean_activation    0.000351  0.001655
conc_NAA+NAAG_mean_activation  0.003778  0.001789
conc_Glu+Gln_mean_activation  -0.002030  0.004911

## 2. Use the FSL FLAME tool to carry out the actual higher-level statistical analysis

The `fsl_mrs.utils.fmrs_tools` package contains a wrapper function for FLAMEO

But first we need to define our second-level design.

### 2.1 Second-level design and contrast matrices

Here we define a design matrix and contrasts to perform a paired t-test between all the betas of the STIM and control conditions.

For information on the formation of these designs please see the [FSL course](https://open.win.ox.ac.uk/pages/fslcourse/website/online_materials.html) and specifically the [FMRI2 E2 video](https://www.youtube.com/watch?v=-nf9Hcthnm8).

In [440]:
# Design matrix
# Design matrix for a paired t-test with 10 subjects.
# The first column encodes the differences, which the others encode the average value of each subject
# across both conditions.
des_mat = np.zeros((20,11), int)
des_mat[:10, 0] = 1
des_mat[10:, 0] = -1
des_mat[:10, 1:] = np.eye(10)
des_mat[10:, 1:] = np.eye(10)
print(des_mat)

# Contrasts
# 1 = STIM>CTRL
# 2 = CTRL>STIM
# 3 = MEAN
# 4 = STIM
# 5 = CTRL
con_mat = np.zeros((5,11), float)
con_mat[0, 0] = 1
con_mat[1, 0] = -1
con_mat[2, 1:] = 0.1
con_mat[3, 0] = 1
con_mat[3, 1:] = 0.1
con_mat[4, 0] = -1
con_mat[4, 1:] = 0.1
print(con_mat)


[[ 1  1  0  0  0  0  0  0  0  0  0]
 [ 1  0  1  0  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0  0  0]
 [ 1  0  0  0  1  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  0  0  0  0]
 [ 1  0  0  0  0  0  1  0  0  0  0]
 [ 1  0  0  0  0  0  0  1  0  0  0]
 [ 1  0  0  0  0  0  0  0  1  0  0]
 [ 1  0  0  0  0  0  0  0  0  1  0]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [-1  1  0  0  0  0  0  0  0  0  0]
 [-1  0  1  0  0  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0  0  0  0  0]
 [-1  0  0  0  1  0  0  0  0  0  0]
 [-1  0  0  0  0  1  0  0  0  0  0]
 [-1  0  0  0  0  0  1  0  0  0  0]
 [-1  0  0  0  0  0  0  1  0  0  0]
 [-1  0  0  0  0  0  0  0  1  0  0]
 [-1  0  0  0  0  0  0  0  0  1  0]
 [-1  0  0  0  0  0  0  0  0  0  1]]
[[ 1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [-1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]
 [ 1.   0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]
 [-1.   0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1 

Note that we don't expect different variance between the paired data so we will use the default (all same group) covariance input.

### 2.2 Run FLAMEO

This will provide the group level contrasts (COPE), variances (VARCOPE), z-statistics and associated p-values, for each of the two contrasts. 

In [441]:
import pandas as pd

p, z, out_cope, out_varcope = fmrs.flameo_wrapper(
        modified_betas,
        modified_var,
        design_mat=des_mat,
        contrast_mat=con_mat)

# Assemble the results into a nicely formatted pandas dataframe
all_stats = np.stack([out_cope, out_varcope, z, p])
columns = pd.MultiIndex.from_product(
        (['COPE', 'VARCOPE', 'z', 'p'],
        ['STIM>CTRL', 'CTRL>STIM', 'MEAN', 'STIM', 'CTRL']),
        names=['Statistics', 'Contrast'])
group_stats = pd.DataFrame(all_stats.reshape(-1, all_stats.shape[-1]), index=columns, columns=all_betas).T

# Filter just to see the mean activation stats
group_stats.filter(regex='mean_activation',axis=0)

Statistics                         COPE                                \
Contrast                      STIM>CTRL CTRL>STIM      MEAN      STIM   
conc_Asc_mean_activation       0.000706 -0.000706 -0.000086  0.000620   
conc_Asp_mean_activation      -0.002853  0.002853 -0.000502 -0.003355   
conc_Cr_mean_activation        0.002075 -0.002075 -0.001202  0.000873   
conc_GABA_mean_activation     -0.001539  0.001539  0.000895 -0.000645   
conc_GPC_mean_activation       0.000454 -0.000454  0.000199  0.000653   
conc_GSH_mean_activation       0.000168 -0.000168 -0.000042  0.000126   
conc_Glc_mean_activation      -0.005150  0.005150 -0.005037 -0.010187   
conc_Gln_mean_activation       0.000806 -0.000806  0.001726  0.002532   
conc_Glu_mean_activation       0.006441 -0.006441  0.004794  0.011236   
conc_Ins_mean_activation      -0.000763  0.000763  0.000261 -0.000502   
conc_Lac_mean_activation       0.004519 -0.004519  0.004074  0.008592   
conc_Mac_mean_activation       0.000062 -0.000062  0.000030  0.000092   
conc_NAA_mean_activation      -0.000308  0.000308 -0.000318 -0.000627   
conc_NAAG_mean_activation     -0.000416  0.000416 -0.000171 -0.000588   
conc_PCh_mean_activation      -0.000508  0.000508 -0.000246 -0.000753   
conc_PCr_mean_activation      -0.001986  0.001986  0.000940 -0.001046   
conc_PE_mean_activation       -0.000254  0.000254 -0.000166 -0.000420   
conc_Scyllo_mean_activation    0.000013 -0.000013  0.000019  0.000033   
conc_Tau_mean_activation       0.001024 -0.001024  0.000473  0.001498   
conc_PCh+GPC_mean_activation  -0.000053  0.000053 -0.000048 -0.000101   
conc_Cr+PCr_mean_activation    0.000078 -0.000078 -0.000259 -0.000181   
conc_NAA+NAAG_mean_activation -0.000725  0.000725 -0.000490 -0.001215   
conc_Glu+Gln_mean_activation   0.007178 -0.007178  0.006549  0.013728   

Statistics                                    VARCOPE                \
Contrast                           CTRL     STIM>CTRL     CTRL>STIM   
conc_Asc_mean_activation      -0.000792  7.925167e-07  7.925167e-07   
conc_Asp_mean_activation       0.002350  3.137942e-06  3.137942e-06   
conc_Cr_mean_activation       -0.003277  1.023893e-06  1.023893e-06   
conc_GABA_mean_activation      0.002434  4.007454e-06  4.007454e-06   
conc_GPC_mean_activation      -0.000255  2.542290e-07  2.542290e-07   
conc_GSH_mean_activation      -0.000210  2.620979e-07  2.620979e-07   
conc_Glc_mean_activation       0.000113  1.010533e-06  1.010533e-06   
conc_Gln_mean_activation       0.000919  1.597641e-06  1.597641e-06   
conc_Glu_mean_activation      -0.001647  1.680798e-06  1.680798e-06   
conc_Ins_mean_activation       0.001024  3.246163e-07  3.246163e-07   
conc_Lac_mean_activation      -0.000445  2.061169e-06  2.061169e-06   
conc_Mac_mean_activation      -0.000033  5.442208e-09  5.442208e-09   
conc_NAA_mean_activation      -0.000010  1.909245e-07  1.909245e-07   
conc_NAAG_mean_activation      0.000245  1.470164e-07  1.470164e-07   
conc_PCh_mean_activation       0.000262  2.530203e-07  2.530203e-07   
conc_PCr_mean_activation       0.002925  9.937768e-07  9.937768e-07   
conc_PE_mean_activation        0.000088  1.320169e-06  1.320169e-06   
conc_Scyllo_mean_activation    0.000006  4.036017e-08  4.036017e-08   
conc_Tau_mean_activation      -0.000551  5.576626e-07  5.576626e-07   
conc_PCh+GPC_mean_activation   0.000005  3.120574e-08  3.120574e-08   
conc_Cr+PCr_mean_activation   -0.000336  1.566390e-07  1.566390e-07   
conc_NAA+NAAG_mean_activation  0.000235  1.873287e-07  1.873287e-07   
conc_Glu+Gln_mean_activation  -0.000629  1.407666e-06  1.407666e-06   

Statistics                                                               \
Contrast                               MEAN          STIM          CTRL   
conc_Asc_mean_activation       7.896932e-07  1.543519e-06  1.620900e-06   
conc_Asp_mean_activation       3.133321e-06  6.190434e-06  6.352090e-06   
conc_Cr_mean_activation        1.021071e-06  1.977776e-06  2.112152e-06   
conc_GABA_mean_activati

## 3. Display results

### 3.1 Format the data for viewing
The above is still quite hard to look at. We can use further pandas tools to format the results more clearly, and also express changes as a percentage of the mean metabolite concentration

In [416]:
def format_df(df_in, metabs_to_plot=None):

    # Remove the individual components of combined metabolites (except Glu & Gln)
    var_tmp = df_in\
    .loc[~(df_in.index.str.contains('_NAA_', case=False)\
        |df_in.index.str.contains('_NAAG_', case=False)\
        |df_in.index.str.contains('_Cr_', case=False)\
        |df_in.index.str.contains('_PCr_', case=False)\
        |df_in.index.str.contains('_PCh_', case=False)\
        |df_in.index.str.contains('_GPC_', case=False)),:]

    var_to_plot = var_tmp.filter(regex='_mean_activation',axis=0)
    var_to_plot.index = var_to_plot.index.str.replace('_mean_activation','')
    var_to_plot.index = var_to_plot.index.str.replace('conc_','')

    tmp_means = var_tmp.filter(regex='(?<!sigma_\d_)beta3',axis=0).COPE.abs().MEAN
    
    tmp_means.index = tmp_means.index.str.replace('conc_','')
    tmp_means.index = tmp_means.index.str.replace('_beta3','')
    # import pdb; pdb.set_trace()
    var_to_plot.COPE = var_to_plot.COPE.divide(tmp_means, axis=0).multiply(100)
    var_to_plot.VARCOPE = var_to_plot.VARCOPE.pow(0.5).divide(tmp_means, axis=0).multiply(100)

    # Drop the mean contrast
    var_to_plot = var_to_plot.drop(['MEAN', 'STIM', 'CTRL'], level=1, axis=1)
    
    var_to_plot = var_to_plot.sort_index()

    var_to_plot = var_to_plot.rename(columns={'COPE':'Effect(%)','VARCOPE':'SD(%)'})

    if metabs_to_plot:
        var_to_plot = var_to_plot.loc[metabs_to_plot]

    return var_to_plot.style\
    .format(formatter={('Effect(%)', 'STIM>CTRL'): "{:+06.2f}", ('Effect(%)', 'CTRL>STIM'): "{:+06.2f}",
                       ('SD(%)', 'STIM>CTRL'): "{:04.1f}", ('SD(%)', 'CTRL>STIM'): "{:04.1f}",
                       ('z', 'STIM>CTRL'):    "{:+05.2f}", ('z', 'CTRL>STIM'):    "{:+05.2f}",
                       ('p', 'STIM>CTRL'):    "{:05.3f}", ('p', 'CTRL>STIM'):    "{:05.3f}"})\
    .highlight_between(subset=['p'],left=0, right=0.05, props='font-weight:bold;color:#e83e8c')\
    .set_table_attributes("style='display:inline'")

The above `format_df` function expresses the COPE and VARCOPE as a % effect and % standard deviation on that value.
The significant p values (P<0.05) are highlighted.

In [442]:
format_df(group_stats)

## 3.2 Plotting

This section displays the group and individual subject time courses as fitted by the dynamic fitting.

There's a lot of plotting code here, but very little data manipulation takes place. Predominantly it selects out the data from the 
pandas Dataframe that we want to plot.

In [460]:
# Lots of utility code in this cell. Not important for understanding.
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 30})

# Assemble single-subject data into dataframe
mi = pd.MultiIndex.from_product([['STIM', 'CTRL'], [f'sub{x}' for x in range(10)]], names=['Condition', 'Subject#'])
single_sub_betas = pd.DataFrame(modified_betas, columns=all_betas, index=mi).T

# Load in original first-level design matrix
design_matrix = pd.read_csv('designmat.csv',header=None).to_numpy()


def plot_2ndlvl(metab, df, percent=True):
    """Returns the temporal response of a metabolite or other free parameter

    :param metab: Regex search string for filtering GLM fitted metabolite/parameter
    :type metab: str
    :param df: stats dataframe
    :type df: pd.DataFrame
    :param percent: Scale to constant beta in %, defaults to True
    :type percent: bool, optional
    """
    metab = metab + 'beta'
    currcopes = df.filter(regex=metab, axis=0).COPE
    curr95ci = df.filter(regex=metab, axis=0).VARCOPE.pow(0.5)
    curr95ci_low = currcopes - curr95ci
    curr95ci_high = currcopes + curr95ci

    constant_term = f'_beta{design_matrix.shape[1]-1}'

    if percent:      
        curr95ci_low = (curr95ci_low / currcopes.filter(regex=constant_term, axis=0).to_numpy())
        curr95ci_low = curr95ci_low.to_numpy()
        
        curr95ci_high = (curr95ci_high / currcopes.filter(regex=constant_term, axis=0).to_numpy())
        curr95ci_high = curr95ci_high.to_numpy()
        
        currcopes = (currcopes / currcopes.filter(regex=constant_term, axis=0).to_numpy())
        currcopes = currcopes.to_numpy()
        return 100 * (np.dot(design_matrix,currcopes)  - 1.0)\
             , 100 * (np.dot(design_matrix,curr95ci_low)  - 1.0)\
             , 100 * (np.dot(design_matrix,curr95ci_high)  - 1.0)
    else:
        currcopes = currcopes.to_numpy()
        curr95ci_low = curr95ci_low.to_numpy()
        curr95ci_high = curr95ci_high.to_numpy()
        return np.dot(design_matrix,currcopes), np.dot(design_matrix,curr95ci_low), np.dot(design_matrix,curr95ci_high)

def indiv_traces(metab, df, percent=True):
    vals = []
    for subj in df.index.unique(level=0):
        p = df.loc[subj].filter(regex=metab+'beta', axis=0).values
        # import pdb; pdb.set_trace()
        val = np.dot(p, design_matrix.T)
        if percent:
            val = 100 * val/p[-1] - 100
        vals.append(val)
    return vals

# ## Plot 
# colors = plt.get_cmap('tab10').colors
# t_axis = np.arange(0,64)

# # Plot glutamate response
# met = 'Glu'
# stim_df = group_stats.xs('STIM',axis=1, level='Contrast')
# plt.plot(plot_2ndlvl(f'_{met}_', stim_df)[0], color=colors[1], label=met, linewidth=5)
# plt.fill_between(
#     t_axis,
#     plot_2ndlvl(f'_{met}_', stim_df)[1],
#     plot_2ndlvl(f'_{met}_', stim_df)[2],
#     color=colors[1],
#     alpha=0.1)

# for it in indiv_traces(f'_{met}_', single_sub_betas.STIM.T, percent=True):
#     plt.plot(it, linestyle=':', color=colors[1], linewidth=0.5)



In [468]:
# Plotly (interactive plotting) utility function
from plotly.subplots import make_subplots
import plotly.graph_objects as go

colors = plt.get_cmap('tab10').colors
def color_t2s(tin, alpha=1):
    tscaled = [255*t for t in tin]
    return f'rgba({tscaled[0]}, {tscaled[1]}, {tscaled[2]}, {alpha})'
line_size = dict(data=3, indivdata=0.5)

def plotly_glm_plot(main_df, indiv_df, stim_or_ctrl, metab_list):

    cur_df = main_df.xs(stim_or_ctrl,axis=1, level='Contrast')

    traces = []
    axis = np.arange(1, 65)
    for idx, met in enumerate(metab_list):
        regexstr = f'_{met}_'
        regexstr = regexstr.replace('+', '\+')

        data = plot_2ndlvl(regexstr, cur_df)
        mean_trace = go.Scatter(x=axis, y=data[0],
                    mode='lines',
                    name=met,
                    legendgroup=met,
                    line=dict(
                        color=color_t2s(colors[idx]),
                        width=line_size['data']),
                    )
        traces.append(mean_trace)
        errors = go.Scatter(
            x=np.concatenate((axis, axis[::-1])) , # x, then x reversed
            y=np.concatenate((data[2], data[1][::-1])), # upper, then lower reversed
            fill='toself',
            fillcolor=color_t2s(colors[idx], 0.2),
            line=dict(color='rgba(255,255,255,0)'),
            hoverinfo="skip",
            name=met + ' CI',
            legendgroup=met,
            showlegend=False
        )
        traces.append(errors)
        for jdx, it in enumerate(indiv_traces(regexstr, indiv_df[stim_or_ctrl].T, percent=True)):
            ind_trace = go.Scatter(
                x=axis, y=it,
                mode='lines',
                name=met + f'_S{jdx}',
                legendgroup=met,
                line=dict(
                    color=color_t2s(colors[idx],0.5),
                    width=line_size['indivdata']),
                showlegend=False)
            traces.append(ind_trace)

    fig = make_subplots(rows=2, cols=1,
                    row_heights=[0.6, 0.4],
                    vertical_spacing=0.1,
                    specs=[[{'type': 'scatter'}], [{'type': 'scatter'}]])

    for trace in traces:
        fig.add_trace(trace, row=1, col=1)

    lw_traces = []
    data = plot_2ndlvl('sigma_0_', cur_df, percent=False)
    lw_traces.append(go.Scatter(x=axis, y=data[0]/np.pi,
                mode='lines',
                name='lw: sigma',
                legendgroup='sigma',
                line=dict(
                    color=color_t2s((0,0,0)),
                    width=line_size['data']),
                ))
    lw_traces.append(go.Scatter(
            x=np.concatenate((axis, axis[::-1])) , # x, then x reversed
            y=np.concatenate((data[2], data[1][::-1]))/np.pi, # upper, then lower reversed
            fill='toself',
            fillcolor=color_t2s((0,0,0), 0.2),
            line=dict(color='rgba(255,255,255,0)'),
            hoverinfo="skip",
            name='lw: sigma CI',
            legendgroup='sigma',
            showlegend=False
        ))
    for jdx, it in enumerate(indiv_traces('sigma_0_', indiv_df[stim_or_ctrl].T, percent=False)):
        lw_traces.append(go.Scatter(
            x=axis, y=it/np.pi,
            mode='lines',
            name=f'lw: sigma_S{jdx}',
            legendgroup='sigma',
            line=dict(
                color=color_t2s((0,0,0),0.5),
                width=line_size['indivdata']),
            showlegend=False))

    for trace in lw_traces:
        fig.add_trace(trace, row=2, col=1)


    fig.update_layout(template='plotly_white')

    fig.update_xaxes(
        row=1,
        tick0=0, dtick=16,
        range=[0, 65])
    fig.update_xaxes(
        row=2,
        title_text='Transient #',
        tick0=0, dtick=16,
        range=[0, 65])

    fig.update_yaxes(row=1,
                    title_text='% change',
                    zeroline=True,
                    zerolinewidth=0.5,
                    zerolinecolor='Gray',
                    range=[-20, 20])

    fig.update_yaxes(row=2,
                    title_text='Gaussian Linewidth (Hz)',
                    range=[3.5, 5.5])


    fig.layout.update({'height': 700})
    fig.update_layout(
        margin=dict(l=30, r=30, t=30, b=30),
    )
    return fig

In [469]:
# Plotting control
stim_or_ctrl = 'STIM'  # 'STIM' or 'CTRL'
metab_list = ['NAA+NAAG', 'Glu', 'Asp', 'Lac', 'Glc']

plotly_glm_plot(group_stats, single_sub_betas, stim_or_ctrl, metab_list)


# Using the command line interface

This final section takes you through the steps needed to replicate the above analysis steps using the FSL-MRS command line scripts, specifically `fmrs_stats`.

## A. Create auxiliary files
We will create four files as inputs to the main `fmrs_stats` script. These are:
1. A list of directories containing the results files.
2. The first-level contrasts, described in a JSON formatted file.
3. The higher-level design matrix, in the FSL VEST format.
4. The higher-level contrast matrix, again in the FSL VEST format.

We start with #1, the list of dynamic fit results.

In [479]:
%%writefile results_list
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub0/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub1/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub2/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub3/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub4/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub5/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub6/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub7/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub8/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub9/stim
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub0/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub1/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub2/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub3/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub4/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub5/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub6/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub7/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub8/ctrl
/Users/wclarke/Documents/Python/fmrs_demo/first_level_results/sub9/ctrl

Overwriting results_list


The next cell creates #2, the first-level contrasts. This is formatted like the interactive python Dataclass, but encoded in the JSON format. Multiple contrasts can be listed. Give the contrast a descriptive name!

In [470]:
%%writefile fl_contrasts.json
[
        {
            "name": "mean_activation",
            "betas": ["beta0", "beta1"],
            "scale": [0.5, 0.5]
        }
]

Overwriting fl_contrasts.json


The last files are #3 and #4, the higher-level designs. These are constructed as above (though here we just include the STIM>CTRL and CTRL>STIM contrasts).

Once written as a text file, they must be converted tot he VEST format using the `Text2Vest` script packaged with FSL.

In [471]:
# %%writefile pttest_design
des_mat = np.zeros((20,11), int)
des_mat[:10, 0] = 1
des_mat[10:, 0] = -1
des_mat[:10, 1:] = np.eye(10)
des_mat[10:, 1:] = np.eye(10)
print(des_mat)
np.savetxt('pttest_design', des_mat)

%sx Text2Vest pttest_design design.mat

con_mat = np.zeros((2,11), int)
con_mat[0, 0] = 1
con_mat[1, 0] = -1
print(con_mat)
np.savetxt('pttest_contrasts', con_mat)

%sx Text2Vest pttest_contrasts design.con

[[ 1  1  0  0  0  0  0  0  0  0  0]
 [ 1  0  1  0  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0  0  0]
 [ 1  0  0  0  1  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  0  0  0  0  0]
 [ 1  0  0  0  0  0  1  0  0  0  0]
 [ 1  0  0  0  0  0  0  1  0  0  0]
 [ 1  0  0  0  0  0  0  0  1  0  0]
 [ 1  0  0  0  0  0  0  0  0  1  0]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [-1  1  0  0  0  0  0  0  0  0  0]
 [-1  0  1  0  0  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0  0  0  0  0]
 [-1  0  0  0  1  0  0  0  0  0  0]
 [-1  0  0  0  0  1  0  0  0  0  0]
 [-1  0  0  0  0  0  1  0  0  0  0]
 [-1  0  0  0  0  0  0  1  0  0  0]
 [-1  0  0  0  0  0  0  0  1  0  0]
 [-1  0  0  0  0  0  0  0  0  1  0]
 [-1  0  0  0  0  0  0  0  0  0  1]]
[[ 1  0  0  0  0  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0  0  0  0]]


[]

## B. Run the command line script
We pass the files created above to the `fmrs_stats` script, as well as defining and output location `--output` and any metabolites to combine `--combine`.

In [473]:
%%sx
fmrs_stats\
    --data results_list\
    --output cmd_group_res\
    --fl-contrasts fl_contrasts.json\
    --combine NAA NAAG\
    --combine Cr PCr\
    --combine PCh GPC\
    --combine Glu Gln\
    --hl-design design.mat\
    --hl-contrasts design.con\
    --hl-contrast-names "STIM>CTRL" "CTRL>STIM"\
    --overwrite

[]

## C. Load the results
There are also folders for each subject/run containing the results of the first-level contrast and metabolite combinations.

In [478]:
# Load the results
cmd_line_df = pd.read_csv('cmd_group_res/group_stats.csv',index_col=0, header=[0,1])

# Format for display
cmd_line_df.filter(regex='mean_activation', axis=0)\
.style\
.format(formatter={('z', 'STIM>CTRL'):    "{:+05.2f}", ('z', 'CTRL>STIM'):    "{:+05.2f}",
                   ('p', 'STIM>CTRL'):    "{:05.3f}", ('p', 'CTRL>STIM'):    "{:05.3f}"})\
.highlight_between(subset=['p'],left=0, right=0.05, props='font-weight:bold;color:#e83e8c')